{% set name = "pygraphviz" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # For some reason there are no .gz files here
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f9850617f9444517641d2e14dfdb99ae8294cf7657be86c031fee8f7c54f863
  patches:
    - patches/0001-Fix-types.patch

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - graphviz
  run:
    - python
    - graphviz

test:
  imports:
    - pygraphviz
    - pygraphviz.tests
  source_files:
    - pygraphviz/tests
  commands:
    - pytest --doctest-modules --durations=10 --pyargs pygraphviz
  requires:
    - pytest

about:
  home: http://pygraphviz.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to Graphviz
  description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and
    visualization package. With PyGraphviz you can create, edit, read, write,
    and draw graphs using Python to access the Graphviz graph data structure
    and layout algorithms. PyGraphviz provides a similar programming
    interface to NetworkX (http://networkx.github.io).
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/pygraphviz/pygraphviz

extra:
  recipe-maintainers:
    - nehaljwani
